# Homework #4
# Project Name: Catch These Hands
# November 20, 2018
# Author 1: Keziah Rezaey - 946961211
# Author 2: Moriah Scott - 993922204

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /media
  static_dir: media
- url: /scripts
  static_dir: scripts
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

# used to make sure youtube API works
